// Define study
const study = lab.util.fromObject({
  "title": "root",
  "type": "lab.flow.Sequence",
  "parameters": {},
  "plugins": [
    {
      "type": "lab.plugins.Metadata",
      "path": undefined
    },
    {
      "type": "lab.plugins.Download",
      "filePrefix": "study",
      "path": undefined
    }
  ],
  "metadata": {
    "title": "",
    "description": "",
    "repository": "",
    "contributors": ""
  },
  "files": {},
  "responses": {},
  "content": [
    {
      "type": "lab.canvas.Screen",
      "content": [
        {
          "type": "i-text",
          "left": -25,
          "top": -135.96,
          "angle": 0,
          "width": 407.3,
          "height": 203.94,
          "stroke": null,
          "strokeWidth": 1,
          "fill": "black",
          "text": "The following test is for the \ngroup assignment of\nWID2003 Cognitive Science\n\nParticipants will be tested for",
          "fontStyle": "normal",
          "fontWeight": "normal",
          "fontSize": 32,
          "fontFamily": "sans-serif",
          "lineHeight": 1.16,
          "textAlign": "center"
        },
        {
          "type": "i-text",
          "left": -25,
          "top": 11.99,
          "angle": 0,
          "width": 472.91,
          "height": 78.11,
          "stroke": null,
          "strokeWidth": 1,
          "fill": "black",
          "text": "Attention & Perception Domain\n",
          "fontStyle": "normal",
          "fontWeight": "bold",
          "fontSize": 32,
          "fontFamily": "sans-serif",
          "lineHeight": 1.16,
          "textAlign": "center"
        },
        {
          "type": "i-text",
          "left": -25,
          "top": 125,
          "angle": 0,
          "width": 660.33,
          "height": 58.58,
          "stroke": null,
          "strokeWidth": 1,
          "fill": "black",
          "text": "The expected duration for this test is approximately 2 minutes.\n(Press \"space\" button to continue)",
          "fontStyle": "italic",
          "fontWeight": "normal",
          "fontSize": "24",
          "fontFamily": "sans-serif",
          "lineHeight": 1.16,
          "textAlign": "center"
        }
      ],
      "viewport": [
        800,
        600
      ],
      "files": {},
      "responses": {
        "keypress(Space)": "next"
      },
      "parameters": {},
      "messageHandlers": {},
      "title": "Introduction"
    },
    {
      "type": "lab.canvas.Screen",
      "content": [
        {
          "type": "i-text",
          "left": 0,
          "top": -225,
          "angle": 0,
          "width": 697.2,
          "height": 78.11,
          "stroke": null,
          "strokeWidth": 1,
          "fill": "black",
          "text": "Before you start the test, \nwe would like to ask for your consent for this test.",
          "fontStyle": "normal",
          "fontWeight": "normal",
          "fontSize": 32,
          "fontFamily": "sans-serif",
          "lineHeight": 1.16,
          "textAlign": "center"
        },
        {
          "type": "i-text",
          "left": 0,
          "top": -50,
          "angle": 0,
          "width": 625.5,
          "height": 162,
          "stroke": null,
          "strokeWidth": 1,
          "fill": "black",
          "text": "We assure that all your personal information\nwill be strictly confidential.\nThe result of the test will only be used for \nassignment purpose.",
          "fontStyle": "italic",
          "fontWeight": "bold",
          "fontSize": 32,
          "fontFamily": "sans-serif",
          "lineHeight": 1.16,
          "textAlign": "center"
        },
        {
          "type": "rect",
          "left": -4.18,
          "top": 150,
          "angle": 0,
          "width": 212.63,
          "height": 68.64,
          "stroke": "#000000",
          "strokeWidth": 1,
          "fill": "#ffffff"
        },
        {
          "type": "i-text",
          "left": 0,
          "top": 150,
          "angle": 0,
          "width": 169.61,
          "height": 36.16,
          "stroke": null,
          "strokeWidth": 1,
          "fill": "black",
          "text": "Yes, I agree",
          "fontStyle": "normal",
          "fontWeight": "normal",
          "fontSize": 32,
          "fontFamily": "sans-serif",
          "lineHeight": 1.16,
          "textAlign": "center"
        },
        {
          "type": "aoi",
          "left": -2.92,
          "top": 150,
          "angle": 0,
          "width": 220.3,
          "height": 71.43,
          "stroke": null,
          "strokeWidth": 1,
          "fill": "rgba(0, 0, 0, 0.2)",
          "label": "agree"
        }
      ],
      "viewport": [
        800,
        600
      ],
      "files": {},
      "responses": {
        "click @agree": "Consent"
      },
      "parameters": {},
      "messageHandlers": {},
      "title": "Consent "
    },
    {
      "type": "lab.canvas.Screen",
      "content": [
        {
          "type": "i-text",
          "left": 0,
          "top": -225,
          "angle": 0,
          "width": 722.28,
          "height": 78.11,
          "stroke": null,
          "strokeWidth": 1,
          "fill": "black",
          "text": "Before the test starts, we would like to ask\nhow long do you spend on playing games per day?",
          "fontStyle": "normal",
          "fontWeight": "normal",
          "fontSize": 32,
          "fontFamily": "sans-serif",
          "lineHeight": 1.16,
          "textAlign": "center"
        },
        {
          "type": "rect",
          "left": -174.51,
          "top": -100,
          "angle": 0,
          "width": 270.62,
          "height": 85.11,
          "stroke": "#000000",
          "strokeWidth": 1,
          "fill": "#ffffff"
        },
        {
          "type": "i-text",
          "left": -175,
          "top": -100,
          "angle": 0,
          "width": 238.39,
          "height": 36.16,
          "stroke": null,
          "strokeWidth": 1,
          "fill": "black",
          "text": "Less than 1 hour",
          "fontStyle": "normal",
          "fontWeight": "normal",
          "fontSize": 32,
          "fontFamily": "sans-serif",
          "lineHeight": 1.16,
          "textAlign": "center"
        },
        {
          "type": "rect",
          "left": -175,
          "top": 37.92,
          "angle": 0,
          "width": 270.62,
          "height": 85.11,
          "stroke": "#000000",
          "strokeWidth": 1,
          "fill": "#ffffff"
        },
        {
          "type": "rect",
          "left": -175,
          "top": 186.83,
          "angle": 0,
          "width": 270.62,
          "height": 85.11,
          "stroke": "#000000",
          "strokeWidth": 1,
          "fill": "#ffffff"
        },
        {
          "type": "i-text",
          "left": -175,
          "top": 37.98,
          "angle": 0,
          "width": 187.69,
          "height": 36.16,
          "stroke": null,
          "strokeWidth": 1,
          "fill": "black",
          "text": "1 to \u003C2 hours",
          "fontStyle": "normal",
          "fontWeight": "normal",
          "fontSize": 32,
          "fontFamily": "sans-serif",
          "lineHeight": 1.16,
          "textAlign": "center"
        },
        {
          "type": "i-text",
          "left": -175,
          "top": 185.89,
          "angle": 0,
          "width": 187.69,
          "height": 36.16,
          "stroke": null,
          "strokeWidth": 1,
          "fill": "black",
          "text": "2 to \u003C4 hours",
          "fontStyle": "normal",
          "fontWeight": "normal",
          "fontSize": 32,
          "fontFamily": "sans-serif",
          "lineHeight": 1.16,
          "textAlign": "center"
        },
        {
          "type": "rect",
          "left": 175,
          "top": -100,
          "angle": 0,
          "width": 270.62,
          "height": 85.11,
          "stroke": "#000000",
          "strokeWidth": 1,
          "fill": "#ffffff"
        },
        {
          "type": "rect",
          "left": 175,
          "top": 35.92,
          "angle": 0,
          "width": 270.62,
          "height": 85.11,
          "stroke": "#000000",
          "strokeWidth": 1,
          "fill": "#ffffff"
        },
        {
          "type": "i-text",
          "left": 175,
          "top": -100,
          "angle": 0,
          "width": 187.69,
          "height": 36.16,
          "stroke": null,
          "strokeWidth": 1,
          "fill": "black",
          "text": "4 to \u003C6 hours",
          "fontStyle": "normal",
          "fontWeight": "normal",
          "fontSize": 32,
          "fontFamily": "sans-serif",
          "lineHeight": 1.16,
          "textAlign": "center"
        },
        {
          "type": "i-text",
          "left": 175,
          "top": 38.98,
          "angle": 0,
          "width": 265.09,
          "height": 36.16,
          "stroke": null,
          "strokeWidth": 1,
          "fill": "black",
          "text": "6 hours and above",
          "fontStyle": "normal",
          "fontWeight": "normal",
          "fontSize": 32,
          "fontFamily": "sans-serif",
          "lineHeight": 1.16,
          "textAlign": "center"
        },
        {
          "type": "aoi",
          "left": -175,
          "top": -101.64,
          "angle": 0,
          "width": 274.37,
          "height": 95.81,
          "stroke": null,
          "strokeWidth": 1,
          "fill": "rgba(0, 0, 0, 0.2)",
          "label": "\u003C1"
        },
        {
          "type": "aoi",
          "left": -172.27,
          "top": 37.38,
          "angle": 0,
          "width": 278.57,
          "height": 99.77,
          "stroke": null,
          "strokeWidth": 1,
          "fill": "rgba(0, 0, 0, 0.2)",
          "label": "1 to \u003C2"
        },
        {
          "type": "aoi",
          "left": -173.3,
          "top": 186.79,
          "angle": 0,
          "width": 278.47,
          "height": 94.88,
          "stroke": null,
          "strokeWidth": 1,
          "fill": "rgba(0, 0, 0, 0.2)",
          "label": "2 to \u003C4"
        },
        {
          "type": "aoi",
          "left": 172.17,
          "top": -100.1,
          "angle": 0,
          "width": 291.41,
          "height": 98.83,
          "stroke": null,
          "strokeWidth": 1,
          "fill": "rgba(0, 0, 0, 0.2)",
          "label": "4 to \u003C6"
        },
        {
          "type": "aoi",
          "left": 177.16,
          "top": 37.13,
          "angle": 0,
          "width": 279.55,
          "height": 99.28,
          "stroke": null,
          "strokeWidth": 1,
          "fill": "rgba(0, 0, 0, 0.2)",
          "label": "\u003E6"
        }
      ],
      "viewport": [
        800,
        600
      ],
      "files": {},
      "responses": {
        "click @\u003C1": "\u003C1",
        "click @1 to \u003C2": "1 to \u003C2",
        "click @2 to \u003C4": "2 to \u003C4",
        "click @4 to \u003C6": "4 to \u003C6",
        "click @\u003E6": "\u003E6"
      },
      "parameters": {},
      "messageHandlers": {},
      "title": "Gaming background"
    },
    {
      "type": "lab.canvas.Screen",
      "content": [
        {
          "type": "i-text",
          "left": 0,
          "top": -125,
          "angle": 0,
          "width": 647.52,
          "height": 203.94,
          "stroke": null,
          "strokeWidth": 1,
          "fill": "black",
          "text": "You will be shown a picture.\nPlease look for as many animals as possible \nfrom the picture.\nCount the number of animals you have found.\nYou will be given 10 seconds.",
          "fontStyle": "normal",
          "fontWeight": "normal",
          "fontSize": 32,
          "fontFamily": "sans-serif",
          "lineHeight": 1.16,
          "textAlign": "center"
        },
        {
          "type": "i-text",
          "left": 0,
          "top": 125,
          "angle": 0,
          "width": 362.57,
          "height": 27.12,
          "stroke": null,
          "strokeWidth": 1,
          "fill": "black",
          "text": "(Press \"space\" button to continue)",
          "fontStyle": "italic",
          "fontWeight": "normal",
          "fontSize": "24",
          "fontFamily": "sans-serif",
          "lineHeight": 1.16,
          "textAlign": "center"
        }
      ],
      "viewport": [
        800,
        600
      ],
      "files": {},
      "responses": {
        "keypress(Space)": "next"
      },
      "parameters": {},
      "messageHandlers": {},
      "title": "Instruction 1"
    },
    {
      "type": "lab.canvas.Screen",
      "content": [
        {
          "type": "image",
          "left": 0,
          "top": 0,
          "angle": 0,
          "width": 634,
          "height": 354,
          "stroke": null,
          "strokeWidth": 0,
          "fill": "black",
          "src": "${ this.files[\"396102FC00000578-3837928-image-a-1_1476439389223.jpg\"] }"
        }
      ],
      "viewport": [
        800,
        600
      ],
      "files": {
        "396102FC00000578-3837928-image-a-1_1476439389223.jpg": "embedded\u002F3d5dd1e8b15ce0557e287f57c42dfd190773d04fea7faa3c320db6ad315936da.jpg"
      },
      "responses": {
        "": ""
      },
      "parameters": {},
      "messageHandlers": {},
      "title": "Picture for Perception",
      "timeout": "10000"
    },
    {
      "type": "lab.canvas.Screen",
      "content": [
        {
          "type": "i-text",
          "left": -14,
          "top": -235.98,
          "angle": 0,
          "width": 515.84,
          "height": 36.16,
          "stroke": null,
          "strokeWidth": 1,
          "fill": "black",
          "text": "How many animals have you found?",
          "fontStyle": "normal",
          "fontWeight": "normal",
          "fontSize": 32,
          "fontFamily": "sans-serif",
          "lineHeight": 1.16,
          "textAlign": "center"
        },
        {
          "type": "rect",
          "left": -225,
          "top": -150,
          "angle": 0,
          "width": 68.12,
          "height": 68.12,
          "stroke": "#000000",
          "strokeWidth": 1,
          "fill": "#ffffff"
        },
        {
          "type": "rect",
          "left": -225,
          "top": -50,
          "angle": 0,
          "width": 68.12,
          "height": 68.12,
          "stroke": "#000000",
          "strokeWidth": 1,
          "fill": "#ffffff"
        },
        {
          "type": "rect",
          "left": -225,
          "top": 50,
          "angle": 0,
          "width": 68.12,
          "height": 68.12,
          "stroke": "#000000",
          "strokeWidth": 1,
          "fill": "#ffffff"
        },
        {
          "type": "rect",
          "left": -225,
          "top": 150,
          "angle": 0,
          "width": 68.12,
          "height": 68.12,
          "stroke": "#000000",
          "strokeWidth": 1,
          "fill": "#ffffff"
        },
        {
          "type": "rect",
          "left": -225,
          "top": 250,
          "angle": 0,
          "width": 68.12,
          "height": 68.12,
          "stroke": "#000000",
          "strokeWidth": 1,
          "fill": "#ffffff"
        },
        {
          "type": "rect",
          "left": -100,
          "top": -150,
          "angle": 0,
          "width": 68.12,
          "height": 68.12,
          "stroke": "#000000",
          "strokeWidth": 1,
          "fill": "#ffffff"
        },
        {
          "type": "rect",
          "left": -100,
          "top": -50,
          "angle": 0,
          "width": 68.12,
          "height": 68.12,
          "stroke": "#000000",
          "strokeWidth": 1,
          "fill": "#ffffff"
        },
        {
          "type": "rect",
          "left": -100,
          "top": 50,
          "angle": 0,
          "width": 68.12,
          "height": 68.12,
          "stroke": "#000000",
          "strokeWidth": 1,
          "fill": "#ffffff"
        },
        {
          "type": "rect",
          "left": -100,
          "top": 150,
          "angle": 0,
          "width": 68.12,
          "height": 68.12,
          "stroke": "#000000",
          "strokeWidth": 1,
          "fill": "#ffffff"
        },
        {
          "type": "rect",
          "left": -100,
          "top": 250,
          "angle": 0,
          "width": 68.12,
          "height": 68.12,
          "stroke": "#000000",
          "strokeWidth": 1,
          "fill": "#ffffff"
        },
        {
          "type": "rect",
          "left": 25,
          "top": 250,
          "angle": 0,
          "width": 68.12,
          "height": 68.12,
          "stroke": "#000000",
          "strokeWidth": 1,
          "fill": "#ffffff"
        },
        {
          "type": "rect",
          "left": 25,
          "top": 150,
          "angle": 0,
          "width": 68.12,
          "height": 68.12,
          "stroke": "#000000",
          "strokeWidth": 1,
          "fill": "#ffffff"
        },
        {
          "type": "rect",
          "left": 25,
          "top": 50,
          "angle": 0,
          "width": 68.12,
          "height": 68.12,
          "stroke": "#000000",
          "strokeWidth": 1,
          "fill": "#ffffff"
        },
        {
          "type": "rect",
          "left": 25,
          "top": -50,
          "angle": 0,
          "width": 68.12,
          "height": 68.12,
          "stroke": "#000000",
          "strokeWidth": 1,
          "fill": "#ffffff"
        },
        {
          "type": "rect",
          "left": 25,
          "top": -150,
          "angle": 0,
          "width": 68.12,
          "height": 68.12,
          "stroke": "#000000",
          "strokeWidth": 1,
          "fill": "#ffffff"
        },
        {
          "type": "rect",
          "left": 150,
          "top": -150,
          "angle": 0,
          "width": 68.12,
          "height": 68.12,
          "stroke": "#000000",
          "strokeWidth": 1,
          "fill": "#ffffff"
        },
        {
          "type": "i-text",
          "left": -225,
          "top": -150,
          "angle": 0,
          "width": 17.8,
          "height": 36.16,
          "stroke": null,
          "strokeWidth": 1,
          "fill": "black",
          "text": "1",
          "fontStyle": "normal",
          "fontWeight": "normal",
          "fontSize": 32,
          "fontFamily": "sans-serif",
          "lineHeight": 1.16,
          "textAlign": "center"
        },
        {
          "type": "i-text",
          "left": -225,
          "top": -50,
          "angle": 0,
          "width": 17.8,
          "height": 36.16,
          "stroke": null,
          "strokeWidth": 1,
          "fill": "black",
          "text": "2",
          "fontStyle": "normal",
          "fontWeight": "normal",
          "fontSize": 32,
          "fontFamily": "sans-serif",
          "lineHeight": 1.16,
          "textAlign": "center"
        },
        {
          "type": "i-text",
          "left": -225,
          "top": 50,
          "angle": 0,
          "width": 17.8,
          "height": 36.16,
          "stroke": null,
          "strokeWidth": 1,
          "fill": "black",
          "text": "3",
          "fontStyle": "normal",
          "fontWeight": "normal",
          "fontSize": 32,
          "fontFamily": "sans-serif",
          "lineHeight": 1.16,
          "textAlign": "center"
        },
        {
          "type": "i-text",
          "left": -225,
          "top": 150,
          "angle": 0,
          "width": 17.8,
          "height": 36.16,
          "stroke": null,
          "strokeWidth": 1,
          "fill": "black",
          "text": "4",
          "fontStyle": "normal",
          "fontWeight": "normal",
          "fontSize": 32,
          "fontFamily": "sans-serif",
          "lineHeight": 1.16,
          "textAlign": "center"
        },
        {
          "type": "i-text",
          "left": -225,
          "top": 250,
          "angle": 0,
          "width": 17.8,
          "height": 36.16,
          "stroke": null,
          "strokeWidth": 1,
          "fill": "black",
          "text": "5",
          "fontStyle": "normal",
          "fontWeight": "normal",
          "fontSize": 32,
          "fontFamily": "sans-serif",
          "lineHeight": 1.16,
          "textAlign": "center"
        },
        {
          "type": "i-text",
          "left": -100,
          "top": 250,
          "angle": 0,
          "width": 35.59,
          "height": 36.16,
          "stroke": null,
          "strokeWidth": 1,
          "fill": "black",
          "text": "10",
          "fontStyle": "normal",
          "fontWeight": "normal",
          "fontSize": 32,
          "fontFamily": "sans-serif",
          "lineHeight": 1.16,
          "textAlign": "center"
        },
        {
          "type": "i-text",
          "left": -100,
          "top": 150,
          "angle": 0,
          "width": 17.8,
          "height": 36.16,
          "stroke": null,
          "strokeWidth": 1,
          "fill": "black",
          "text": "9",
          "fontStyle": "normal",
          "fontWeight": "normal",
          "fontSize": 32,
          "fontFamily": "sans-serif",
          "lineHeight": 1.16,
          "textAlign": "center"
        },
        {
          "type": "i-text",
          "left": -100,
          "top": 50,
          "angle": 0,
          "width": 17.8,
          "height": 36.16,
          "stroke": null,
          "strokeWidth": 1,
          "fill": "black",
          "text": "8",
          "fontStyle": "normal",
          "fontWeight": "normal",
          "fontSize": 32,
          "fontFamily": "sans-serif",
          "lineHeight": 1.16,
          "textAlign": "center"
        },
        {
          "type": "i-text",
          "left": -100,
          "top": -50,
          "angle": 0,
          "width": 17.8,
          "height": 36.16,
          "stroke": null,
          "strokeWidth": 1,
          "fill": "black",
          "text": "7",
          "fontStyle": "normal",
          "fontWeight": "normal",
          "fontSize": 32,
          "fontFamily": "sans-serif",
          "lineHeight": 1.16,
          "textAlign": "center"
        },
        {
          "type": "i-text",
          "left": -100,
          "top": -150,
          "angle": 0,
          "width": 17.8,
          "height": 36.16,
          "stroke": null,
          "strokeWidth": 1,
          "fill": "black",
          "text": "6",
          "fontStyle": "normal",
          "fontWeight": "normal",
          "fontSize": 32,
          "fontFamily": "sans-serif",
          "lineHeight": 1.16,
          "textAlign": "center"
        },
        {
          "type": "i-text",
          "left": 25,
          "top": -150,
          "angle": 0,
          "width": 33.22,
          "height": 36.16,
          "stroke": null,
          "strokeWidth": 1,
          "fill": "black",
          "text": "11",
          "fontStyle": "normal",
          "fontWeight": "normal",
          "fontSize": 32,
          "fontFamily": "sans-serif",
          "lineHeight": 1.16,
          "textAlign": "center"
        },
        {
          "type": "i-text",
          "left": 25,
          "top": -50,
          "angle": 0,
          "width": 35.59,
          "height": 36.16,
          "stroke": null,
          "strokeWidth": 1,
          "fill": "black",
          "text": "12",
          "fontStyle": "normal",
          "fontWeight": "normal",
          "fontSize": 32,
          "fontFamily": "sans-serif",
          "lineHeight": 1.16,
          "textAlign": "center"
        },
        {
          "type": "i-text",
          "left": 25,
          "top": 50,
          "angle": 0,
          "width": 35.59,
          "height": 36.16,
          "stroke": null,
          "strokeWidth": 1,
          "fill": "black",
          "text": "13",
          "fontStyle": "normal",
          "fontWeight": "normal",
          "fontSize": 32,
          "fontFamily": "sans-serif",
          "lineHeight": 1.16,
          "textAlign": "center"
        },
        {
          "type": "i-text",
          "left": 25,
          "top": 150,
          "angle": 0,
          "width": 35.59,
          "height": 36.16,
          "stroke": null,
          "strokeWidth": 1,
          "fill": "black",
          "text": "14",
          "fontStyle": "normal",
          "fontWeight": "normal",
          "fontSize": 32,
          "fontFamily": "sans-serif",
          "lineHeight": 1.16,
          "textAlign": "center"
        },
        {
          "type": "i-text",
          "left": 25,
          "top": 250,
          "angle": 0,
          "width": 35.59,
          "height": 36.16,
          "stroke": null,
          "strokeWidth": 1,
          "fill": "black",
          "text": "15",
          "fontStyle": "normal",
          "fontWeight": "normal",
          "fontSize": 32,
          "fontFamily": "sans-serif",
          "lineHeight": 1.16,
          "textAlign": "center"
        },
        {
          "type": "i-text",
          "left": 150,
          "top": -150,
          "angle": 0,
          "width": 35.59,
          "height": 36.16,
          "stroke": null,
          "strokeWidth": 1,
          "fill": "black",
          "text": "16",
          "fontStyle": "normal",
          "fontWeight": "normal",
          "fontSize": 32,
          "fontFamily": "sans-serif",
          "lineHeight": 1.16,
          "textAlign": "center"
        },
        {
          "type": "aoi",
          "left": -225.67,
          "top": -150.61,
          "angle": 0,
          "width": 72.14,
          "height": 72.14,
          "stroke": null,
          "strokeWidth": 1,
          "fill": "rgba(0, 0, 0, 0.2)",
          "label": "1"
        },
        {
          "type": "aoi",
          "left": -225,
          "top": -50,
          "angle": 0,
          "width": 72.14,
          "height": 72.14,
          "stroke": null,
          "strokeWidth": 1,
          "fill": "rgba(0, 0, 0, 0.2)",
          "label": "2"
        },
        {
          "type": "aoi",
          "left": -225,
          "top": 50,
          "angle": 0,
          "width": 72.14,
          "height": 72.14,
          "stroke": null,
          "strokeWidth": 1,
          "fill": "rgba(0, 0, 0, 0.2)",
          "label": "3"
        },
        {
          "type": "aoi",
          "left": -225,
          "top": 150,
          "angle": 0,
          "width": 72.14,
          "height": 72.14,
          "stroke": null,
          "strokeWidth": 1,
          "fill": "rgba(0, 0, 0, 0.2)",
          "label": "4"
        },
        {
          "type": "aoi",
          "left": -225,
          "top": 250,
          "angle": 0,
          "width": 72.14,
          "height": 72.14,
          "stroke": null,
          "strokeWidth": 1,
          "fill": "rgba(0, 0, 0, 0.2)",
          "label": "5"
        },
        {
          "type": "aoi",
          "left": -100,
          "top": 250,
          "angle": 0,
          "width": 72.14,
          "height": 72.14,
          "stroke": null,
          "strokeWidth": 1,
          "fill": "rgba(0, 0, 0, 0.2)",
          "label": "10"
        },
        {
          "type": "aoi",
          "left": -100,
          "top": 150,
          "angle": 0,
          "width": 72.14,
          "height": 72.14,
          "stroke": null,
          "strokeWidth": 1,
          "fill": "rgba(0, 0, 0, 0.2)",
          "label": "9"
        },
        {
          "type": "aoi",
          "left": -100,
          "top": 50,
          "angle": 0,
          "width": 72.14,
          "height": 72.14,
          "stroke": null,
          "strokeWidth": 1,
          "fill": "rgba(0, 0, 0, 0.2)",
          "label": "8"
        },
        {
          "type": "aoi",
          "left": -100,
          "top": -50,
          "angle": 0,
          "width": 72.14,
          "height": 72.14,
          "stroke": null,
          "strokeWidth": 1,
          "fill": "rgba(0, 0, 0, 0.2)",
          "label": "7"
        },
        {
          "type": "aoi",
          "left": -100,
          "top": -150,
          "angle": 0,
          "width": 72.14,
          "height": 72.14,
          "stroke": null,
          "strokeWidth": 1,
          "fill": "rgba(0, 0, 0, 0.2)",
          "label": "6"
        },
        {
          "type": "aoi",
          "left": 25,
          "top": -150,
          "angle": 0,
          "width": 72.14,
          "height": 72.14,
          "stroke": null,
          "strokeWidth": 1,
          "fill": "rgba(0, 0, 0, 0.2)",
          "label": "11"
        },
        {
          "type": "aoi",
          "left": 25,
          "top": -50,
          "angle": 0,
          "width": 72.14,
          "height": 72.14,
          "stroke": null,
          "strokeWidth": 1,
          "fill": "rgba(0, 0, 0, 0.2)",
          "label": "12"
        },
        {
          "type": "aoi",
          "left": 25,
          "top": 50,
          "angle": 0,
          "width": 72.14,
          "height": 72.14,
          "stroke": null,
          "strokeWidth": 1,
          "fill": "rgba(0, 0, 0, 0.2)",
          "label": "13"
        },
        {
          "type": "aoi",
          "left": 25,
          "top": 150,
          "angle": 0,
          "width": 72.14,
          "height": 72.14,
          "stroke": null,
          "strokeWidth": 1,
          "fill": "rgba(0, 0, 0, 0.2)",
          "label": "14"
        },
        {
          "type": "aoi",
          "left": 25,
          "top": 250,
          "angle": 0,
          "width": 72.14,
          "height": 72.14,
          "stroke": null,
          "strokeWidth": 1,
          "fill": "rgba(0, 0, 0, 0.2)",
          "label": "15"
        },
        {
          "type": "aoi",
          "left": 150,
          "top": -150,
          "angle": 0,
          "width": 72.14,
          "height": 72.14,
          "stroke": null,
          "strokeWidth": 1,
          "fill": "rgba(0, 0, 0, 0.2)",
          "label": "16"
        }
      ],
      "viewport": [
        800,
        600
      ],
      "files": {},
      "responses": {
        "click @1": "1",
        "click @2": "2",
        "click @3": "3",
        "click @4": "4",
        "click @5": "5",
        "click @6": "6",
        "click @7": "7",
        "click @8": "8",
        "click @9": "9",
        "click @10": "10",
        "click @11": "11",
        "click @12": "12",
        "click @13": "13",
        "click @14": "14",
        "click @15": "15",
        "click @16": "16"
      },
      "parameters": {},
      "messageHandlers": {},
      "title": "Answer for Perception"
    },
    {
      "type": "lab.canvas.Screen",
      "content": [
        {
          "type": "i-text",
          "left": 0,
          "top": -50,
          "angle": 0,
          "width": 748.91,
          "height": 497.56,
          "stroke": null,
          "strokeWidth": 1,
          "fill": "black",
          "text": "You will be shown a list of words\npainted in different colours.\n\nPlease read the colours of the words,\ninstead of the words themselves.\nThe sequence of reading is up to you.\n\nFor example,\n\nRead it \"blue\" instead of red.\n\nPress space after you have done reading everything.",
          "fontStyle": "normal",
          "fontWeight": "normal",
          "fontSize": 32,
          "fontFamily": "sans-serif",
          "lineHeight": 1.16,
          "textAlign": "center"
        },
        {
          "type": "i-text",
          "left": 0,
          "top": 50,
          "angle": 0,
          "width": 46.25,
          "height": 36.16,
          "stroke": null,
          "strokeWidth": 1,
          "fill": "#0070d9",
          "text": "red",
          "fontStyle": "normal",
          "fontWeight": "normal",
          "fontSize": 32,
          "fontFamily": "sans-serif",
          "lineHeight": 1.16,
          "textAlign": "center"
        },
        {
          "type": "i-text",
          "left": 0,
          "top": 250,
          "angle": 0,
          "width": 483.42,
          "height": 36.16,
          "stroke": null,
          "strokeWidth": 1,
          "fill": "black",
          "text": "(Press \"space\" button to continue)",
          "fontStyle": "italic",
          "fontWeight": "normal",
          "fontSize": "24",
          "fontFamily": "sans-serif",
          "lineHeight": 1.16,
          "textAlign": "center"
        }
      ],
      "viewport": [
        800,
        600
      ],
      "files": {},
      "responses": {
        "keypress(Space)": "next"
      },
      "parameters": {},
      "messageHandlers": {},
      "title": "Instruction 2"
    },
    {
      "type": "lab.canvas.Screen",
      "content": [
        {
          "type": "i-text",
          "left": -275,
          "top": -225,
          "angle": 0,
          "width": 46.25,
          "height": 36.16,
          "stroke": null,
          "strokeWidth": 1,
          "fill": "#12864e",
          "text": "red",
          "fontStyle": "normal",
          "fontWeight": "normal",
          "fontSize": 32,
          "fontFamily": "sans-serif",
          "lineHeight": 1.16,
          "textAlign": "center"
        },
        {
          "type": "i-text",
          "left": -275,
          "top": -150,
          "angle": 0,
          "width": 46.25,
          "height": 36.16,
          "stroke": null,
          "strokeWidth": 1,
          "fill": "#0070d9",
          "text": "red",
          "fontStyle": "normal",
          "fontWeight": "normal",
          "fontSize": 32,
          "fontFamily": "sans-serif",
          "lineHeight": 1.16,
          "textAlign": "center"
        },
        {
          "type": "i-text",
          "left": -275,
          "top": -75,
          "angle": 0,
          "width": 81.84,
          "height": 36.16,
          "stroke": null,
          "strokeWidth": 1,
          "fill": "#d6341a",
          "text": "green",
          "fontStyle": "normal",
          "fontWeight": "normal",
          "fontSize": 32,
          "fontFamily": "sans-serif",
          "lineHeight": 1.16,
          "textAlign": "center"
        },
        {
          "type": "i-text",
          "left": -275,
          "top": 0,
          "angle": 0,
          "width": 60.5,
          "height": 36.16,
          "stroke": null,
          "strokeWidth": 1,
          "fill": "#f8eb35",
          "text": "blue",
          "fontStyle": "normal",
          "fontWeight": "normal",
          "fontSize": 32,
          "fontFamily": "sans-serif",
          "lineHeight": 1.16,
          "textAlign": "center"
        },
        {
          "type": "i-text",
          "left": -275,
          "top": 75,
          "angle": 0,
          "width": 74.7,
          "height": 36.16,
          "stroke": null,
          "strokeWidth": 1,
          "fill": "#0070d9",
          "text": "violet",
          "fontStyle": "normal",
          "fontWeight": "normal",
          "fontSize": 32,
          "fontFamily": "sans-serif",
          "lineHeight": 1.16,
          "textAlign": "center"
        },
        {
          "type": "i-text",
          "left": -275,
          "top": 225,
          "angle": 0,
          "width": 88.92,
          "height": 36.16,
          "stroke": null,
          "strokeWidth": 1,
          "fill": "#57df26",
          "text": "yellow",
          "fontStyle": "normal",
          "fontWeight": "normal",
          "fontSize": 32,
          "fontFamily": "sans-serif",
          "lineHeight": 1.16,
          "textAlign": "center"
        },
        {
          "type": "i-text",
          "left": -25,
          "top": -150,
          "angle": 0,
          "width": 74.7,
          "height": 36.16,
          "stroke": null,
          "strokeWidth": 1,
          "fill": "#d6341a",
          "text": "black",
          "fontStyle": "normal",
          "fontWeight": "normal",
          "fontSize": 32,
          "fontFamily": "sans-serif",
          "lineHeight": 1.16,
          "textAlign": "center"
        },
        {
          "type": "i-text",
          "left": -25,
          "top": -75,
          "angle": 0,
          "width": 74.7,
          "height": 36.16,
          "stroke": null,
          "strokeWidth": 1,
          "fill": "#0e297c",
          "text": "white",
          "fontStyle": "normal",
          "fontWeight": "normal",
          "fontSize": 32,
          "fontFamily": "sans-serif",
          "lineHeight": 1.16,
          "textAlign": "center"
        },
        {
          "type": "i-text",
          "left": -25,
          "top": 0,
          "angle": 0,
          "width": 85.41,
          "height": 36.16,
          "stroke": null,
          "strokeWidth": 1,
          "fill": "#e619df",
          "text": "indigo",
          "fontStyle": "normal",
          "fontWeight": "normal",
          "fontSize": 32,
          "fontFamily": "sans-serif",
          "lineHeight": 1.16,
          "textAlign": "center"
        },
        {
          "type": "i-text",
          "left": -25,
          "top": 150,
          "angle": 0,
          "width": 60.5,
          "height": 36.16,
          "stroke": null,
          "strokeWidth": 1,
          "fill": "#e00b0b",
          "text": "blue",
          "fontStyle": "normal",
          "fontWeight": "normal",
          "fontSize": 32,
          "fontFamily": "sans-serif",
          "lineHeight": 1.16,
          "textAlign": "center"
        },
        {
          "type": "i-text",
          "left": -25,
          "top": 225,
          "angle": 0,
          "width": 58.7,
          "height": 36.16,
          "stroke": null,
          "strokeWidth": 1,
          "fill": "#000000",
          "text": "pink",
          "fontStyle": "normal",
          "fontWeight": "normal",
          "fontSize": 32,
          "fontFamily": "sans-serif",
          "lineHeight": 1.16,
          "textAlign": "center"
        },
        {
          "type": "i-text",
          "left": -25,
          "top": -225,
          "angle": 0,
          "width": 99.64,
          "height": 36.16,
          "stroke": null,
          "strokeWidth": 1,
          "fill": "#000000",
          "text": "orange",
          "fontStyle": "normal",
          "fontWeight": "normal",
          "fontSize": 32,
          "fontFamily": "sans-serif",
          "lineHeight": 1.16,
          "textAlign": "center"
        },
        {
          "type": "i-text",
          "left": 200,
          "top": -225,
          "angle": 0,
          "width": 81.84,
          "height": 36.16,
          "stroke": null,
          "strokeWidth": 1,
          "fill": "#27e73e",
          "text": "green",
          "fontStyle": "normal",
          "fontWeight": "normal",
          "fontSize": 32,
          "fontFamily": "sans-serif",
          "lineHeight": 1.16,
          "textAlign": "center"
        },
        {
          "type": "i-text",
          "left": 200,
          "top": -150,
          "angle": 0,
          "width": 58.7,
          "height": 36.16,
          "stroke": "#e2188e",
          "strokeWidth": 1,
          "fill": "#e2188e",
          "text": "pink",
          "fontStyle": "normal",
          "fontWeight": "normal",
          "fontSize": 32,
          "fontFamily": "sans-serif",
          "lineHeight": 1.16,
          "textAlign": "center"
        },
        {
          "type": "i-text",
          "left": 200,
          "top": -75,
          "angle": 0,
          "width": 88.95,
          "height": 36.16,
          "stroke": null,
          "strokeWidth": 1,
          "fill": "#c617de",
          "text": "purple",
          "fontStyle": "normal",
          "fontWeight": "normal",
          "fontSize": 32,
          "fontFamily": "sans-serif",
          "lineHeight": 1.16,
          "textAlign": "center"
        },
        {
          "type": "i-text",
          "left": 200,
          "top": 0,
          "angle": 0,
          "width": 60.5,
          "height": 36.16,
          "stroke": "#fcbb0a",
          "strokeWidth": 1,
          "fill": "#fcbb0a",
          "text": "blue",
          "fontStyle": "normal",
          "fontWeight": "normal",
          "fontSize": 32,
          "fontFamily": "sans-serif",
          "lineHeight": 1.16,
          "textAlign": "center"
        },
        {
          "type": "i-text",
          "left": 200,
          "top": 75,
          "angle": 0,
          "width": 88.92,
          "height": 36.16,
          "stroke": null,
          "strokeWidth": 1,
          "fill": "#18cda0",
          "text": "yellow",
          "fontStyle": "normal",
          "fontWeight": "normal",
          "fontSize": 32,
          "fontFamily": "sans-serif",
          "lineHeight": 1.16,
          "textAlign": "center"
        },
        {
          "type": "i-text",
          "left": 200,
          "top": 150,
          "angle": 0,
          "width": 74.7,
          "height": 36.16,
          "stroke": null,
          "strokeWidth": 1,
          "fill": "#efd00b",
          "text": "black",
          "fontStyle": "normal",
          "fontWeight": "normal",
          "fontSize": 32,
          "fontFamily": "sans-serif",
          "lineHeight": 1.16,
          "textAlign": "center"
        },
        {
          "type": "i-text",
          "left": 200,
          "top": 225,
          "angle": 0,
          "width": 85.41,
          "height": 36.16,
          "stroke": null,
          "strokeWidth": 1,
          "fill": "#ac15d5",
          "text": "indigo",
          "fontStyle": "normal",
          "fontWeight": "normal",
          "fontSize": 32,
          "fontFamily": "sans-serif",
          "lineHeight": 1.16,
          "textAlign": "center"
        },
        {
          "type": "i-text",
          "left": -275,
          "top": 150,
          "angle": 0,
          "width": 99.64,
          "height": 36.16,
          "stroke": null,
          "strokeWidth": 1,
          "fill": "#fcbb0a",
          "text": "orange",
          "fontStyle": "normal",
          "fontWeight": "normal",
          "fontSize": 32,
          "fontFamily": "sans-serif",
          "lineHeight": 1.16,
          "textAlign": "center"
        },
        {
          "type": "i-text",
          "left": -25,
          "top": 75,
          "angle": 0,
          "width": 88.95,
          "height": 36.16,
          "stroke": null,
          "strokeWidth": 1,
          "fill": "#a8ca09",
          "text": "purple",
          "fontStyle": "normal",
          "fontWeight": "normal",
          "fontSize": 32,
          "fontFamily": "sans-serif",
          "lineHeight": 1.16,
          "textAlign": "center"
        }
      ],
      "viewport": [
        800,
        600
      ],
      "files": {},
      "responses": {
        "keypress(Space)": "next"
      },
      "parameters": {},
      "messageHandlers": {},
      "title": "Picture for Attention"
    },
    {
      "type": "lab.canvas.Screen",
      "content": [
        {
          "type": "i-text",
          "left": -11,
          "top": -125,
          "angle": 0,
          "width": 463.11,
          "height": 162,
          "stroke": null,
          "strokeWidth": 1,
          "fill": "black",
          "text": "Thank you for sitting for the test.\nYour participation is appreciated.\n\nHave a nice day.",
          "fontStyle": "normal",
          "fontWeight": "normal",
          "fontSize": 32,
          "fontFamily": "sans-serif",
          "lineHeight": 1.16,
          "textAlign": "center"
        },
        {
          "type": "i-text",
          "left": -350,
          "top": 125,
          "angle": 0,
          "width": 664.88,
          "height": 203.94,
          "stroke": null,
          "strokeWidth": 1,
          "fill": "black",
          "text": "What to do after\n1) Press \"space\" button to download the result.\n2) Name the file using your name\n3) Send your result to the corresponding \n    person in charge.",
          "fontStyle": "italic",
          "fontWeight": "normal",
          "fontSize": 32,
          "fontFamily": "sans-serif",
          "lineHeight": 1.16,
          "textAlign": "left"
        }
      ],
      "viewport": [
        800,
        600
      ],
      "files": {},
      "responses": {
        "keypress(Space)": "next"
      },
      "parameters": {},
      "messageHandlers": {},
      "title": "Ending"
    }
  ]
})

// Let's go!
study.run()